[package]
name = "vulkano_text"
version = "0.10.0"
edition = "2018"
authors = ["Rukai <rubickent@gmail.com>"]
description = "Render text with the DejaVu font using the Vulkano library."
license = "MIT"
repository = "https://github.com/rukai/vulkano-text"
keywords = ["vulkano", "text", "font"]

[dependencies]
rusttype = { version = "0.7", features = ["gpu_cache"] }
vulkano = "0.13"
vulkano-shaders = "0.13"

[dev-dependencies]
winit = "0.19"
vulkano-win = "0.13"
