[package]
name = "vulkano_text"
version = "0.6.1"
authors = ["Rukai <rubickent@gmail.com>"]
description = "Render text with the DejaVu font using the Vulkano library."
license = "MIT"
repository = "https://github.com/rukai/vulkano-text"
keywords = ["vulkano", "text", "font"]

[dependencies]
rusttype = "0.2"
vulkano = "0.7"
vulkano-shader-derive = "0.7"

[dev-dependencies]
winit = "0.7"
vulkano-win = "0.7"
